---
title: "cleanData"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

# import all data
```{r}
# assumes working directory is where the original datasheet lives
allData <- read.csv("experiment1data.csv", 
                    header = TRUE,
                    na.strings = c("", " ", "na", "NA"))
allData

# count number of rows in the dataframe for future reference
nallData <- nrow(allData)
```

# remove bad data
```{r}
cleanData <- allData[!is.na(allData$DaysTreat),]      # na days treatment
cleanData <- cleanData[!is.na(cleanData$RelTreat),]   # na relative treatment
cleanData <- cleanData[!is.na(cleanData$SocTreat),]   # na social treatment
cleanData <- cleanData[!is.na(cleanData$DateColl),]   # na collection date
cleanData

# count rows in cleaned dataset to compare to initial data
ncleanData <- nrow(cleanData)
print(paste(nallData - ncleanData, "out of", nallData, "bees have been removed due to NA values treatment and collection day, unreplicated collection dates, and experimental error/inconsistencies", sep = " "))
```

# add RelDayTreat column to combine treatment information into one variable
```{r}
# add RelDayTreat column that combines RelTreat & DaysTreat
cleanData$RelDayTreat <- paste(cleanData$RelTreat, cleanData$DaysTreat)

# make RelDayTreat an ordered factor so I can see groups in order on plots
cleanData$RelDayTreat <- factor(cleanData$RelDayTreat, levels = c("gas 1",
                                                                  "gas 4", 
                                                                  "gas 7",
                                                                  "offspring 1",
                                                                  "offspring 4", 
                                                                  "offspring 7"))
```

# code columns as correct variable types
```{r}
cleanData$Pulled <- as.character(cleanData$Pulled)           # make pulled date a character first (was previously integer)
cleanData$Pulled <- as.Date(cleanData$Pulled, "%Y%m%d")      # then convert pulled to date

cleanData$DateColl <- as.character(cleanData$DateColl)       # make collection date a character first (was previously integer)
cleanData$DateColl <- as.Date(cleanData$DateColl, "%Y%m%d")  # then convert to date

cleanData$FirstOffEcl <- as.character(cleanData$FirstOffEcl)       # make mate date a character first (was previously integer)
cleanData$FirstOffEcl <- as.Date(cleanData$FirstOffEcl, "%Y%m%d")  # then convert to date
```

# check sample sizes for each group
```{r}
# count the number of samples in each treatment group
cleanSampleSizes <- cleanData %>% group_by(RelDayTreat, SocTreat) %>% tally()

# plot the number of samples in each treatment group
ggplot(cleanSampleSizes, aes(x = RelDayTreat, y = n, fill = SocTreat)) +
  geom_bar(stat = "identity", position = position_dodge()) + 
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(breaks = c(2, 4, 6, 8, 10))

# if there is an NA treatment group on the x axis, that means not all treatment groups were included in the factor list in the previous chunk
cleanData

```

# add wing average, queen age, brood number columns to enable including these in future analyses
```{r}
# make a new column with wing averages to approximate size
for (i in 1:nrow(cleanData)) {
  cleanData$WingAvg[i] <- mean(c(cleanData$Wing1[i], cleanData$Wing2[i]), na.rm = TRUE) }

# make a new column with queen age
cleanData$QueenAge <- cleanData$DateColl - cleanData$Pulled  # date collected - date pulled = queen age at collection
cleanData

# change early queen nEggs from NA to 0 (left blank on datasheet imported as NA, but really they should be 0)
for (i in 1:nrow(cleanData)) {
  if (cleanData$RelTreat[i] == "gas" & is.na(cleanData$nEggs[i])) {
    cleanData$nEggs[i] <- 0
  }
}

# make a new column with total number of offspring
for (i in 1:nrow(cleanData)) {
  cleanData$nOffspring[i] <- sum(cleanData$nEggs[i],
                                 cleanData$HealthyLarv[i],
                                 cleanData$BlacLarv[i],
                                 cleanData$PrePupae[i],
                                 cleanData$Pupae[i],
                                 cleanData$nMale[i],
                                 na.rm = TRUE)
}
```

# export cleanData file for use in analyses
```{r}
# export cleanData file to working directory
write.csv(cleanData, file = "clean1.csv")
cleanData
```

# age range of late queens
```{r}
# look only at late queens
lateData <- cleanData[cleanData$RelTreat == "offspring",]

# make date variables dates
lateData$Pulled <- as.Date(lateData$Pulled, "%Y-%m-%d")
lateData$FirstOffEcl <- as.Date(lateData$FirstOffEcl, "%Y-%m-%d")
lateData$DateColl <- as.Date(lateData$DateColl, "%Y-%m-%d")

# date of first offspring - date pulled = queen age at first offsrping
lateData$queenAgeOff <- lateData$FirstOffEcl - lateData$Pulled

# date of collection - date pulled = queen age at collection
lateData$queenAgeColl <- lateData$DateColl - lateData$Pulled

# maximum & minimum ages at eclosion
maxAge <- max(lateData$queenAgeOff, na.rm = TRUE)
print(paste("The oldest queen was", maxAge, "days old at the time of offspring eclosion.", sep = " "))
minAge <- min(lateData$queenAgeOff, na.rm = TRUE)
print(paste("The youngest queen was", minAge, "days old at the time of offspring eclosion.", sep = " "))

# maximum & minimum ages at collection
maxAge <- max(lateData$queenAgeColl, na.rm = TRUE)
print(paste("The oldest queen was", maxAge, "days old at the time of colleciton.", sep = " "))
minAge <- min(lateData$queenAgeColl, na.rm = TRUE)
print(paste("The youngest queen was", minAge, "days old at the time of collection.", sep = " "))
```
